/*
 * This Java source file was generated by the Gradle 'init' task.
 */


public class AppTest {
/*    @Test public void testAppHasAGreeting() {
        MyApplication classUnderTest = new MyApplication();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());*/
   
}
